name: Publish Image Using Commit Hash

on:
  push:
    branches:
      - master

jobs:
  push:
    name: Publish Image
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Push the image on the registry
      uses: Ferlab-Ste-Justine/action-push-image@master
      with:
        username: chusj
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        image: chusj/arranger
        tag_source: sha
        location: .
        dockerfile: Dockerfile
      